# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - BREAKING CHANGE
    - title: Exciting New Features 🎉
      labels:
        - "feat*"
    - title: Other Changes
      labels:
        - "*"
