---
  # Required fields
  samples: "tests/input_files/samples.tsv"
  output_dir: "results"
  log_dir: "logs"
  cluster_log_dir: "logs/cluster"
  kallisto_indexes: "results/kallisto_indexes"
  salmon_indexes: "results/salmon_indexes"
  star_indexes: "results/star_indexes"
  alfa_indexes: "results/alfa_indexes"
  # Optional fields
  rule_config: "tests/input_files/rule_config.yaml"
  report_description: "No description provided by user"
  report_logo: "images/logo.128px.png"
  report_url: "https://zavolan.biozentrum.unibas.ch/"
  author_name: "NA"
  author_email: "NA"
...
