jobscript: "../slurm-jobscript.sh"
cluster-generic-submit-cmd: "../slurm-submit.py"
cluster-generic-status-cmd: "../slurm-status.py"
cluster-generic-sidecar-cmd: "../slurm-sidecar.py"
cluster-generic-cancel-cmd: "scancel"
max-jobs-per-second: 1
max-status-checks-per-second: 10
snakefile: "../../workflow/Snakefile"
cores: 256
jobs: 256
latency-wait: 60
printshellcmds: true
rerun-incomplete: true
use-conda: true
default-resources: mem_mb=1024
restart-times: 3
keep-going: true
notemp: false
no-hooks: true
verbose: true
