name: zarp
dependencies:
  - bioconda::bedtools
  - bioconda::snakemake>=9.8
  - bioconda::snakefmt
  - conda-forge::biopython
  - conda-forge::graphviz
  - conda-forge::pyopenssl>=23.2.0
  - conda-forge::python>=3.11
  - conda-forge::unzip
