name: zarp
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz=2.40.1
  - jinja2=3.0.3
  - mamba=0.16.0
  - networkx=2.4
  - pip=20.0.2
  - pygments=2.6.1
  - pygraphviz=1.3
  - python=3.7.4
  - singularity=3.5.2
  - pip:
    - pandas==1.0.1
    - snakemake==7.2.1

