snakefile: "../../workflow/Snakefile"
cores: 4
printshellcmds: true
rerun-incomplete: true
use-conda: true
conda-frontend: conda
keep-going: true
restart-times: 3
notemp: true
no-hooks: true
verbose: true
