snakefile: "../../workflow/Snakefile"
cores: 4
printshellcmds: true
rerun-incomplete: true
use-conda: true
keep-going: true
default-resources: mem_mb=1024
restart-times: 3
notemp: false
no-hooks: true
verbose: true
