import pandas as pd

configfile: "config.yaml"

localrules: finish

#################################################################################
### Final rule
#################################################################################

rule finish:
	input:
		final_sample = expand()

##################################################################################
# Execution dependend on sequencing mode
##################################################################################

include: 'paired_end.snakefile'
include: 'single_end.snakefile'
