name: Docs

on:
  push:
    branches: [main, dev, docs-describe-zarp-outputs]
  workflow_dispatch:

jobs:

  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout ZARP repository
        uses: actions/checkout@v4

      - name: Setup Miniforge with ZARP environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: install/environment.dev.yml
          miniforge-version: latest
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: zarp

      - name: Display Conda and environment info
        run: |
          conda info -a
          conda list

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install doc requirements
        run: pip install -r docs/requirements.txt

      - name: Publish docs
        run: mkdocs gh-deploy --force --clean --verbose
