name: DEBUGGING

on:
  pull_request:
    branches:
      - main
      - dev

jobs:

  singularity-test:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout zarp repository
        uses: actions/checkout@v4

      - name: Setup miniconda & zarp env
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: install/environment.yml
          miniforge-version: latest
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: zarp

      - name: Install Singularity
        run: conda env update -p $CONDA_PREFIX -f install/environment.root.yml

      - name: Test Simple Singularity Exec
        run: |
          singularity --version
          singularity pull docker://alpine:latest
          singularity exec alpine_latest.sif echo "Hello from Singularity" 

  snakemake-graphs-format:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout zarp repository
        uses: actions/checkout@v4

      - name: Setup miniconda & zarp env
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: install/environment.yml
          miniforge-version: latest
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: zarp

      - name: Update zarp env with root. packages
        run: conda env update -p $CONDA_PREFIX -f install/environment.root.yml

      - name: Update zarp env with dev. packages
        run: conda env update -p $CONDA_PREFIX -f install/environment.dev.yml

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list

      - name: Run test script for snakemake format
        run: bash tests/test_format/test_snakefmt.sh

      - name: Run test script for snakemake lint
        run: bash tests/test_format/test_snakemake_lint.sh

      - name: Run test script for snakemake rulegraph
        run: bash tests/test_create_rule_graph/test.sh

      - name: Run test script for snakemake DAG
        run: bash tests/test_create_dag_image/test.sh

  integration-conda:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout zarp repository
        uses: actions/checkout@v4

      - name: Setup miniconda & zarp env
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: install/environment.yml
          miniforge-version: latest
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: zarp

      - name: Update zarp env with dev. packages
        run: conda env update -p $CONDA_PREFIX -f install/environment.dev.yml

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list

      - name: Run test script
        run: bash tests/test_integration_workflow_with_conda/test.local.sh

      - name: Run htsinfer test script
        run: bash tests/test_htsinfer_with_conda/test.local.sh

      - name: Run SRA downloads workflow
        run: bash tests/test_sra_download_with_conda/test.local.sh

